/**
 * Generates frontend/pages/shared/related-url-resolver.js from the canonical
 * TypeScript route definitions in src/shared/route-definitions.ts.
 *
 * Run via: npm run generate:routes
 * Also runs automatically as part of: npm run build  |  npm test  |  npm run publish
 *
 * The output file is committed — keeping it generated (not hand-written) ensures
 * the client and server resolvers can never silently diverge.
 *
 * Exports:
 *   buildContent()    — returns the file content as a string (used by tests and the sync check)
 *   GENERATED_PATH    — absolute path to the output file
 */

import { writeFileSync } from "fs";
import { resolve } from "path";
import { ROUTE_MAP, TYPE_ALIASES } from "../shared/route-definitions";

export const GENERATED_PATH = resolve(
  __dirname,
  "../../frontend/pages/shared/related-url-resolver.js",
);

export function buildContent(): string {
  const routeMapLines = Object.entries(ROUTE_MAP)
    .map(([type, path]) => `  ${JSON.stringify(type)}: ${JSON.stringify(path)},`)
    .join("\n");

  const aliasLines = Object.entries(TYPE_ALIASES)
    .map(([alias, canonical]) => `  ${JSON.stringify(alias)}: ${JSON.stringify(canonical)},`)
    .join("\n");

  return `// AUTO-GENERATED — do not edit this file directly.
// Source of truth: src/shared/route-definitions.ts
// Regenerate:      npm run generate:routes
//
// Rule: to add a new record type, edit route-definitions.ts first,
// then run generate:routes. Adding a type alias that maps to an
// unknown canonical type is a TypeScript compile error.

const ROUTE_MAP = {
${routeMapLines}
};

const TYPE_ALIASES = {
${aliasLines}
};

export function normalizeType(type) {
  if (!type) return "Letter";
  return TYPE_ALIASES[type] ?? type;
}

export function resolveRelatedUrl(type, id) {
  const canonical = normalizeType(type);
  return (ROUTE_MAP[canonical] ?? "/letters") + "/" + id;
}
`;
}

if (require.main === module) {
  writeFileSync(GENERATED_PATH, buildContent(), "utf-8");
  console.log(`[generate:routes] Wrote ${GENERATED_PATH}`);
}
