/**
 * VeteransLedger · Timeline page
 * Reads /public/data/timeline/events.json — generated by the Admin publish
 * pipeline. Falls back gracefully when the file is missing or empty.
 *
 * Backward-compatible: handles both ISO date strings ("1939-09-01") produced
 * by the pipeline and the older human-readable strings ("1 September 1939")
 * that may exist in hand-authored snapshots.
 */

import { applyRecordTranslation } from "/pages/shared/translation-loader.js";
import { onLocaleChange } from "/pages/shared/i18n.js";

const yearNav   = document.getElementById("timeline-year-nav");
const yearLoader = document.getElementById("year-loader");
const track     = document.getElementById("timeline-track");
const filters   = document.getElementById("timeline-filters");

let allEvents    = [];
let activeYear   = null;
let activeCategory = "all";

// ── Date helpers ──────────────────────────────────────────────────────────────

function parseYear(ev) {
  if (ev.year) return Number(ev.year);
  if (ev.date) {
    // ISO: "1939-09-01"
    const iso = ev.date.match(/^(\d{4})-\d{2}-\d{2}/);
    if (iso) return Number(iso[1]);
    // Fallback: let the browser try
    const d = new Date(ev.date);
    if (!isNaN(d)) return d.getFullYear();
  }
  return null;
}

function formatDate(ev) {
  if (!ev.date) return "";
  // ISO format — parse as local midnight to avoid UTC-shift issues
  if (/^\d{4}-\d{2}-\d{2}$/.test(ev.date)) {
    const [y, m, d] = ev.date.split("-").map(Number);
    return new Date(y, m - 1, d).toLocaleDateString("en-GB", { day: "numeric", month: "short" });
  }
  // Already human-readable (legacy static JSON)
  return ev.date;
}

function formatDateRange(ev) {
  const start = formatDate(ev);
  if (!ev.endDate) return start;
  const end = formatDate({ date: ev.endDate });
  return start && end ? `${start} – ${end}` : start || end;
}

// ── Init ──────────────────────────────────────────────────────────────────────

async function init() {
  if (yearLoader) yearLoader.remove();

  try {
    const res = await fetch("/public/data/timeline/events.json");
    if (res.ok) {
      const data = await res.json();
      allEvents = Array.isArray(data) ? data : (data.events ?? []);
    }
  } catch (_) {}

  buildYearNav();

  filters?.addEventListener("click", (e) => {
    const btn = e.target.closest(".filter-btn");
    if (!btn) return;
    activeCategory = btn.dataset.filter || "all";
    filters.querySelectorAll(".filter-btn").forEach((b) =>
      b.classList.toggle("is-active", b === btn));
    render();
  });

  // Default to the first year that has events, or 1939 if none
  const years = availableYears();
  selectYear(years.includes(1939) ? 1939 : (years[0] ?? 1939));

  onLocaleChange(() => render());
}

// ── Year navigation ───────────────────────────────────────────────────────────

function availableYears() {
  const set = new Set();
  allEvents.forEach((ev) => {
    const y = parseYear(ev);
    if (y) set.add(y);
  });
  return [...set].sort((a, b) => a - b);
}

function buildYearNav() {
  if (!yearNav) return;
  yearNav.innerHTML = "";

  const years = availableYears();
  // If no DB events yet, fall back to the classic 1933–1945 range so the
  // page still looks right when loaded before first publish
  const list = years.length ? years : [
    1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930,
    1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
    1943, 1944, 1945,
  ];

  list.forEach((year) => {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "timeline-year-btn";
    btn.textContent = year;
    btn.dataset.year = year;
    btn.setAttribute("role", "tab");
    btn.setAttribute("aria-selected", "false");
    btn.addEventListener("click", () => selectYear(year));
    yearNav.appendChild(btn);
  });
}

function selectYear(year) {
  activeYear = year;
  yearNav?.querySelectorAll(".timeline-year-btn").forEach((btn) => {
    const active = +btn.dataset.year === year;
    btn.classList.toggle("is-active", active);
    btn.setAttribute("aria-selected", String(active));
  });
  render();
}

// ── Render ────────────────────────────────────────────────────────────────────

function render() {
  if (!track) return;
  track.innerHTML = "";

  const events = allEvents.filter((e) => {
    const year = parseYear(e);
    if (activeYear && year !== activeYear) return false;
    if (activeCategory !== "all" && e.category !== activeCategory) return false;
    return true;
  });

  if (!events.length) {
    track.innerHTML = `<div class="empty-state">
      <div class="empty-state__icon" aria-hidden="true">✛</div>
      <p class="empty-state__title">No events found</p>
      <p class="empty-state__text">No records match this filter for ${activeYear ?? "this period"}.</p>
    </div>`;
    return;
  }

  // Group by year, sorted chronologically within each year
  const groups = {};
  events.forEach((e) => {
    const y = parseYear(e) ?? "?";
    if (!groups[y]) groups[y] = [];
    groups[y].push(e);
  });

  // Sort events within each year by date
  Object.values(groups).forEach((group) => {
    group.sort((a, b) => {
      if (a.date && b.date) return a.date.localeCompare(b.date);
      return 0;
    });
  });

  Object.keys(groups)
    .sort((a, b) => Number(a) - Number(b))
    .forEach((year) => {
      const groupEl = document.createElement("div");
      groupEl.className = "timeline-group";
      groupEl.innerHTML = `
        <div class="timeline-group__year">
          <span class="timeline-group__year-label">${year}</span>
          <span class="timeline-group__year-line"></span>
        </div>`;

      groups[year].forEach((ev) => {
        const dateStr = formatDateRange(ev);
        const evEl = document.createElement("div");
        evEl.className = "timeline-event";
        evEl.innerHTML = `
          <div class="timeline-event__date">${dateStr}</div>
          <div class="timeline-event__body">
            ${ev.category ? `<div class="timeline-event__category">${escHtml(ev.category)}</div>` : ""}
            <h3 class="timeline-event__title">${escHtml(ev.title || ev.event || "")}</h3>
            ${ev.summary || ev.description
              ? `<p class="timeline-event__summary">${escHtml(ev.summary || ev.description)}</p>`
              : ""}
            ${ev.location ? `<div class="timeline-event__location">📍 ${escHtml(ev.location)}</div>` : ""}
            ${ev.significance
              ? `<p class="timeline-event__significance" style="font-size:var(--text-xs,11px);color:var(--text-muted);margin-top:6px;font-style:italic;">${escHtml(ev.significance)}</p>`
              : ""}
          </div>`;
        groupEl.appendChild(evEl);

        // Timeline events use their real DB id directly (no slug layer,
        // unlike Records/Entities) — see toTimelineJson() in
        // src/modules/publish/validators/timeline.conformance.ts.
        if (ev.id) {
          applyRecordTranslation(evEl, "timeline_event", ev.id, {
            titleSelector: ".timeline-event__title",
            summarySelector: ".timeline-event__summary",
            noticeAnchor: ".timeline-event__body",
          });
        }
      });

      track.appendChild(groupEl);
    });
}

function escHtml(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

init();
